# Generated by Django 2.2.7 on 2019-11-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.DecimalField(decimal_places=15, default='', help_text='Latitude', max_digits=19)),
                ('Longitude', models.DecimalField(decimal_places=15, default='', help_text='Longitude', max_digits=19)),
                ('Unique_Squirrel_ID', models.CharField(default='', help_text='Unique_Squirrel_ID', max_length=15)),
                ('Date', models.DateField(default='2000-01-01', help_text='Date')),
                ('Age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], default='', help_text='Age', max_length=50)),
                ('Shift', models.CharField(help_text='Shift', max_length=2)),
                ('Primary_Fur_Color', models.CharField(help_text='Primary_Fur_Color', max_length=50)),
                ('Location', models.CharField(help_text='Location1', max_length=50)),
                ('Specific_Location', models.CharField(help_text='Specific_Location', max_length=50)),
                ('Other_Activities', models.CharField(help_text='Other_Activities', max_length=50)),
                ('Running', models.BooleanField(default=False, help_text='Running')),
                ('Chasing', models.BooleanField(default=False, help_text='Chasing')),
                ('Climbing', models.BooleanField(default=False, help_text='Climbing')),
                ('Eating', models.BooleanField(default=False, help_text='Eating')),
                ('Foraging', models.BooleanField(default=False, help_text='Foraging')),
                ('Kuks', models.BooleanField(default=False, help_text='Kuks')),
                ('Quaas', models.BooleanField(default=False, help_text='Quaas')),
                ('Moans', models.BooleanField(default=False, help_text='Moans')),
                ('Tail_flags', models.BooleanField(default=False, help_text='Tail_flags')),
                ('Tail_twitches', models.BooleanField(default=False, help_text='Tail_twitches')),
                ('Approaches', models.BooleanField(default=False, help_text='Approaches')),
                ('Indifferent', models.BooleanField(default=False, help_text='Indifferent')),
                ('Runs_from', models.BooleanField(default=False, help_text='Runs_from')),
            ],
        ),
    ]
