# Generated by Django 2.2.7 on 2019-12-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('Unknown', 'Unknown')], default='Unknown', help_text='Age', max_length=50),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Primary_Fur_Color',
            field=models.CharField(default='Unknown', help_text='Primary_Fur_Color', max_length=50),
        ),
    ]
